# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: imagedoesntexistpod
  namespace: default
  labels:
    app: failedPod
spec:
  containers:
  - name: imagedoesntexisterrorpod
    image: nginx:v1
    ports:
    - containerPort: 80
      name: http
  

